version: "3"

networks:
  app-net:
    driver: bridge

services:
  db:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    networks:
      - app-net
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "db"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=secret
      - MYSQL_HOST=db
    networks:
      - app-net
